# basic options
title: blog 2
author: zorbathegreek
email: thecarbonshifters@gmail.com
description: A wonderful site
twitter_username: TheCarbonShifters
github_username:  zorbathegreek

# Build settings
markdown: kramdown
theme: minima
