# basic options
title: blog 2
author: zorbathegreek
email: thecarbonshifters@gmail.com
description: A site to turn Your Carbon Footprint around
twitter_username: CarbonShifters
github_username:  zorbathegreek

# Build settings
markdown: kramdown
theme: minima
