# basic options
title: blog 2
author: zorbathegreek
email: simm.anthony@gmail.com
description: A wonderful site
twitter_username: thecarbonshifters
github_username:  zorbathegreek

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
